#!/usr/bin/env bash
set -eu
export SCRIPT=$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0") 
export SRC=/${SCRIPT}.cc
export BINDIR=$(dirname "$SCRIPT")/bin
export BIN=$BINDIR/$HOSTNAME/$(basename "${SRC%.cc}")
(cd "$(dirname "$0")" && make SHELL='bash -eu' -s -f - "$BIN" -j <<'EOF')
-include $(BIN).d
CXXFLAGS= $(if $(DEBUG),-g -O0,-O2) -march=native -pipe -std=c++1y -Wall -Wextra -pedantic -I/usr/local/include -I/usr/local/include/bamtools -I/usr/include/bamtools
LDLIBS= -L/usr/local/lib -lbamtools -lboost_program_options -lboost_filesystem -lboost_system -lboost_regex
$(BIN) : $(SRC) $(SCRIPT)
	mkdir -p "$$(dirname "$@")" && \
	TMP=$$(TMPDIR=$$(dirname "$@") mktemp -t "tmpXXXXXX") && \
	$(LINK.cc) -MMD -MP -MF "$$TMP.d" -MQ "$@" "$<" $(LDLIBS) -o "$$TMP" && \
	mv "$$TMP.d" "$@.d" && \
	mv "$$TMP" "$@" && \
	chmod +x "$@"
EOF
exec -a "$0" "$BIN" "$@"
